'use strict';
(()=>{
const names=['Pan tostado','Lechuga','Tomate','Queso','Carne a la plancha','Huevo','Champiñones','Cebolla','Pollo a la plancha','Pepino','Arroz','Zanahoria'];
const ranks=[{name:'Aprendiz',at:0},{name:'Ayudante',at:5},{name:'Cocinero',at:15},{name:'Sous-chef',at:30},{name:'Chef de Bellwood',at:60}];
const recipes=[{name:'Sándwich de la casa',ids:[0,3,2,0],rank:0},{name:'Ensalada del jardín',ids:[1,2,9],rank:0},{name:'Tostada de Neko',ids:[0,5,2],rank:0},{name:'Sándwich de pollo',ids:[0,1,8,2,0],rank:1},{name:'Bowl de la bahía',ids:[10,8,9,11],rank:1},{name:'Club Bellwood',ids:[0,1,4,3,2,0],rank:2},{name:'Arroz del bosque',ids:[10,6,7,5,11],rank:2},{name:'Especial de la chef',ids:[0,1,8,3,7,2,0],rank:3},{name:'Bowl degustación',ids:[10,8,6,9,11,5,7],rank:4}];
const rankOf=n=>ranks.reduce((a,r,i)=>n>=r.at?i:a,0);
class Order{constructor(recipe){this.recipe=recipe;this.items=[];this.served=false;}add(id){if(this.served||this.items.length>=this.recipe.ids.length)return false;this.items.push(id);return true;}undo(){if(!this.served)this.items.pop();}clear(){if(!this.served)this.items=[];}valid(){return !this.served&&this.items.length===this.recipe.ids.length&&this.items.every((v,i)=>v===this.recipe.ids[i]);}serve(){if(!this.valid())return false;this.served=true;return true;}}
const root=document.createElement('section');root.id='cooking';root.className='hidden';root.innerHTML='<canvas id="cookcanvas" width="960" height="540"></canvas><header><div><small>BELLWOOD · COCINA</small><b id="cookrank"></b><span id="cookprogress"></span></div><strong id="cookcoins"></strong><button id="cookpause" aria-label="Pausar cocina">Ⅱ</button></header><section id="cookticket"><small>COMANDA · +10 MONEDAS</small><h2 id="cookname"></h2><p>Sigue el orden de arriba abajo.</p><ol id="cooksteps"></ol></section><div id="cookstatus" role="status">Arrastra los ingredientes al plato.</div><button id="cookundo">DESHACER</button><button id="cookclear">LIMPIAR</button><button id="cookserve">SERVIR · +10</button><div id="cookcover" class="hidden"><article><small>BELLWOOD</small><h2 id="cookheading"></h2><p id="cookdetail"></p><div id="cookactions"></div></article></div>';
document.querySelector('#game').append(root);const $=s=>root.querySelector(s),c=$('#cookcanvas').getContext('2d');let active=false,paused=false,opts=null,order=null,drag=null,selected=0,pose=0,poseEnd=0,serial=0,lastRecipe=-1,elapsed=0;
const slot=i=>({x:266+(i%6)*112,y:388+Math.floor(i/6)*72,w:104,h:64});
function ingredient(ctx,id,x,y,w,h){const f=OMNI_V9_FRAMES.food[id],s=Math.min(w/f[2],h/f[3]);ctx.imageSmoothingEnabled=false;ctx.drawImage(opts.food,...f,x+(w-f[2]*s)/2,y+(h-f[3]*s)/2,f[2]*s,f[3]*s);}
function updateUI(){const progress=opts.progress(),rank=rankOf(progress.orders),next=ranks[rank+1];$('#cookrank').textContent=ranks[rank].name;$('#cookprogress').textContent=next?progress.orders+' / '+next.at+' pedidos · próximo: '+next.name:progress.orders+' pedidos · puesto máximo';$('#cookcoins').textContent='◈ '+progress.coins;$('#cookname').textContent=order.recipe.name;$('#cooksteps').replaceChildren();order.recipe.ids.forEach((id,i)=>{const li=document.createElement('li'),icon=document.createElement('canvas');icon.width=48;icon.height=32;ingredient(icon.getContext('2d'),id,0,0,48,32);li.append(icon);const label=document.createElement('span');label.textContent=(i+1)+'. '+names[id];li.append(label);li.className=i<order.items.length?(order.items[i]===id?'correct':'wrong'):'';$('#cooksteps').append(li);});$('#cookserve').disabled=paused||order.served;$('#cookundo').disabled=paused||!order.items.length||order.served;$('#cookclear').disabled=$('#cookundo').disabled;}
function message(s){$('#cookstatus').textContent=s;}
function nextOrder(){const pool=recipes.filter(r=>r.rank<=rankOf(opts.progress().orders));let index=serial%pool.length;if(index===lastRecipe&&pool.length>1)index=(index+1)%pool.length;lastRecipe=index;serial++;order=new Order(pool[index]);paused=false;drag=null;pose=3;poseEnd=elapsed+.8;$('#cookcover').classList.add('hidden');message('Arrastra los ingredientes al plato, en el orden de la comanda.');updateUI();}
function bindAction(b,fn){b.onpointerdown=e=>{e.preventDefault();e.stopPropagation();};b.onpointerup=e=>{e.preventDefault();e.stopPropagation();if(!b.disabled)fn();};b.onclick=e=>{if(e.detail===0&&!b.disabled)fn();};}
function cover(title,detail,buttons){$('#cookheading').textContent=title;$('#cookdetail').textContent=detail;$('#cookactions').replaceChildren();for(const [label,fn]of buttons){const b=document.createElement('button');b.textContent=label;bindAction(b,fn);$('#cookactions').append(b);}$('#cookcover').classList.remove('hidden');}
function serve(){if(!active||paused)return false;if(!order.serve()){message('Revisa la comanda: ingredientes y orden deben coincidir. Puedes deshacer.');return false;}const before=rankOf(opts.progress().orders);opts.onOrder();const after=rankOf(opts.progress().orders);paused=true;pose=7;poseEnd=Infinity;drag=null;updateUI();cover(after>before?'¡Ascenso: '+ranks[after].name+'!':'¡Pedido entregado!',order.recipe.name+'\n+10 monedas · '+opts.progress().orders+' pedidos completados\n'+(after>before?'Neko confía en ti: nuevas recetas disponibles.':'Maid Neko: «¡Perfecto! Así se cocina en Bellwood.»'),[['SIGUIENTE PEDIDO',nextOrder],['TERMINAR TURNO',leave]]);return true;}
function pause(){if(!active||paused)return;paused=true;drag=null;updateUI();cover('Pausa de cocina','Tu plato se queda en la mesa. Las monedas de pedidos entregados ya están guardadas.',[['CONTINUAR',()=>{paused=false;$('#cookcover').classList.add('hidden');updateUI();}],['TERMINAR TURNO',leave]]);}
function leave(){if(!active)return;active=false;paused=false;drag=null;root.classList.add('hidden');document.querySelector('#game').classList.remove('cookingmode');const cb=opts.onExit;opts=null;order=null;cb();}
function start(options){if(active)return false;opts=options;active=true;paused=false;serial=opts.progress().orders;lastRecipe=-1;root.classList.remove('hidden');document.querySelector('#game').classList.add('cookingmode');nextOrder();return true;}
function xy(e){const r=root.getBoundingClientRect();return {x:(e.clientX-r.left)*960/r.width,y:(e.clientY-r.top)*540/r.height};}
function drop(p){if(!drag)return;const d=drag;drag=null;if(Math.hypot(p.x-d.startX,p.y-d.startY)<12)return;const inside=((p.x-556)/216)**2+((p.y-245)/108)**2<1;if(inside){if(order.add(d.id)){pose=order.items.length%2?4:5;poseEnd=elapsed+.9;message(order.items.length===order.recipe.ids.length?'Plato montado. Revisa la comanda y pulsa SERVIR.':'Añadido: '+names[d.id]+'.');window.OmniSound?.play('step');}else message('El plato está lleno. Deshaz un ingrediente o sirve.');updateUI();}}
const canvas=$('#cookcanvas');canvas.addEventListener('pointerdown',e=>{if(!active||paused||drag)return;const p=xy(e);for(let i=0;i<names.length;i++){const s=slot(i);if(p.x>=s.x&&p.x<=s.x+s.w&&p.y>=s.y&&p.y<=s.y+s.h){e.preventDefault();canvas.setPointerCapture(e.pointerId);drag={id:i,pointer:e.pointerId,x:p.x,y:p.y,startX:p.x,startY:p.y};break;}}});canvas.addEventListener('pointermove',e=>{if(drag?.pointer!==e.pointerId)return;const p=xy(e);drag.x=p.x;drag.y=p.y;});canvas.addEventListener('pointerup',e=>{if(drag?.pointer===e.pointerId)drop(xy(e));});for(const ev of ['pointercancel','lostpointercapture'])canvas.addEventListener(ev,e=>{if(drag?.pointer===e.pointerId)drag=null;});
bindAction($('#cookserve'),serve);bindAction($('#cookpause'),pause);bindAction($('#cookundo'),()=>{order.undo();updateUI();message('Último ingrediente retirado.');});bindAction($('#cookclear'),()=>{order.clear();updateUI();message('Plato limpio. Puedes empezar otra vez.');});
document.addEventListener('keydown',e=>{if(!active)return;e.stopImmediatePropagation();if(e.key==='Escape'){e.preventDefault();pause();}},true);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',pause);
function text(s,x,y,size=12,col='#ffe7bb',align='center'){c.font='bold '+size+'px Arial';c.textAlign=align;c.fillStyle=col;c.fillText(s,x,y);}
function render(now){elapsed=now/1000;if(active&&opts){c.imageSmoothingEnabled=false;c.drawImage(opts.background,0,0,960,540);c.fillStyle='#081f27dd';c.fillRect(0,0,960,540);c.fillStyle='#402d24';c.fillRect(251,111,690,266);for(let i=0;i<8;i++){c.fillStyle=i%2?'#4c3528':'#473125';c.fillRect(252,114+i*32,688,30);}c.strokeStyle='#ad8960';c.lineWidth=2;c.strokeRect(252,112,688,264);c.fillStyle='#231d22';c.beginPath();c.ellipse(556,276,209,75,0,0,Math.PI*2);c.fill();c.fillStyle=drag?'#f7e4b8':'#dddad0';c.beginPath();c.ellipse(556,246,215,96,0,0,Math.PI*2);c.fill();c.strokeStyle='#aaa392';c.lineWidth=4;c.beginPath();c.ellipse(556,246,181,70,0,0,Math.PI*2);c.stroke();if(!order.items.length)text('SUELTA AQUÍ',556,250,19,'#7d735b');order.items.forEach((id,i)=>{const n=order.items.length,x=order.recipe.ids[0]===0?493:426+(i%3)*82,y=order.recipe.ids[0]===0?258-i*13:200+Math.floor(i/3)*37;ingredient(c,id,x,y,126,64);});
const f=OMNI_V9_FRAMES.neko[elapsed<poseEnd?pose:Math.floor(elapsed*1.3)%2?0:3],h=180,w=f[2]/f[3]*h;c.drawImage(opts.neko,...f,857-w/2,305-h,w,h);text('MAID NEKO',850,324,11,'#b7f5bc');text('A TU RITMO',850,343,8,'#b3b6a5');
for(let i=0;i<names.length;i++){const s=slot(i);c.fillStyle='#193e46';c.fillRect(s.x,s.y,s.w,s.h);c.strokeStyle='#50797a';c.lineWidth=1;c.strokeRect(s.x,s.y,s.w,s.h);ingredient(c,i,s.x+22,s.y+2,60,43);text(names[i],s.x+s.w/2,s.y+57,9,'#e6eddf');}if(drag){c.globalAlpha=.93;ingredient(c,drag.id,drag.x-54,drag.y-54,108,92);c.globalAlpha=1;}}requestAnimationFrame(render);}
requestAnimationFrame(render);window.OmniCooking={start,pause,leave,rankOf,ranks,recipes,get active(){return active;},get paused(){return paused;}};if(location.search.includes('qa=1'))Object.assign(OmniCooking,{Order,serve,slot,getOrder:()=>order,nextOrder});
})();
