'use strict';
// Audio.currentTime is the sole rhythm clock: rendering cannot accumulate drift.
(()=>{const chart=window.OMNI_CHART,colors=['#72e3f2','#bca0ff','#ff98ca','#c4f785'],arrows=['←','↓','↑','→'];
const modes={easy:{name:'FÁCIL',window:.24,good:.185,sick:.11,perfect:.055,loss:5,lead:2.8},normal:{name:'NORMAL',window:.205,good:.155,sick:.095,perfect:.05,loss:7,lead:2.35},hard:{name:'DIFÍCIL',window:.175,good:.13,sick:.085,perfect:.042,loss:9,lead:2.05}};
class RhythmSession{constructor(mode){this.mode=mode;this.rules=modes[mode];this.notes=chart.charts[mode].map(([t,lane])=>({t,lane,result:null}));this.health=80;this.score=0;this.combo=0;this.maxCombo=0;this.counts={perfect:0,sick:0,good:0,bad:0,miss:0,empty:0};this.first=0;this.done=false;this.won=false;this.lastPress=[-99,-99,-99,-99];this.lastJudge=null;}
 judge(kind,n,time){if(this.done||n?.result)return;if(n)n.result=kind;this.counts[kind]++;const values={perfect:1000,sick:800,good:500,bad:150,miss:0,empty:0};this.score+=values[kind];if(['miss','bad','empty'].includes(kind))this.combo=0;else this.combo++;this.maxCombo=Math.max(this.maxCombo,this.combo);this.health=Math.max(0,Math.min(100,this.health+(kind==='perfect'?3:kind==='sick'?2:kind==='miss'?-this.rules.loss:kind==='bad'?-2:kind==='empty'?-3:0)));this.lastJudge={kind,time,lane:n?.lane??-1};if(this.health<=0){this.done=true;this.won=false;}}
 advance(time){if(this.done)return;for(let i=this.first;i<this.notes.length;i++){const n=this.notes[i];if(n.t+this.rules.window>=time)break;if(!n.result)this.judge('miss',n,time);if(this.done)break;}while(this.first<this.notes.length&&this.notes[this.first].result)this.first++;if(time>=chart.duration&&this.notes.every(n=>n.result)){this.done=true;this.won=this.health>0;}}
 press(lane,time){if(this.done||time<0||time-this.lastPress[lane]<.075)return null;this.lastPress[lane]=time;this.advance(time);if(this.done)return null;let candidate=null,error=Infinity;for(let i=this.first;i<this.notes.length;i++){const n=this.notes[i];if(n.t>time+this.rules.window)break;if(n.result||n.lane!==lane)continue;const d=Math.abs(n.t-time);if(d<error){candidate=n;error=d;}}if(!candidate){this.judge('empty',null,time);return 'empty';}const kind=error<=this.rules.perfect?'perfect':error<=this.rules.sick?'sick':error<=this.rules.good?'good':'bad';this.judge(kind,candidate,time);return kind;}
 result(){return {mode:this.mode,won:this.won,score:this.score,health:this.health,maxCombo:this.maxCombo,counts:{...this.counts},total:this.notes.length,accuracy:Math.round(10000*(this.counts.perfect+this.counts.sick*.9+this.counts.good*.6+this.counts.bad*.2)/this.notes.length)/100};}}
const song=new Audio(chart.audio);song.preload='metadata';let active=false,paused=false,options=null,session=null,reported=false,lastFrame=0,pose=0,poseUntil=0,flash=[0,0,0,0],notice='',calibration=Math.max(-.15,Math.min(.15,Number(localStorage.getItem('omni-rhythm-offset'))||0));
const root=document.createElement('section');root.id='rhythm';root.className='hidden';root.innerHTML='<canvas id="rhythmcanvas" width="960" height="540"></canvas><div class="rhythm-top"><div><b id="rhythmtitle"></b><small id="rhythmtrack">BTS · RUN · CONCIERTO BAHÍA</small><div class="rhythm-health"><i id="rhythmhp"></i></div><span id="rhythmhealth"></span></div><div id="rhythmscore"></div></div><button id="rhythmpause" aria-label="Pausar batalla">Ⅱ</button><div id="rhythmlanes">'+arrows.map((a,i)=>'<button data-lane="'+i+'" style="--lane:'+colors[i]+'" aria-label="Flecha '+['izquierda','abajo','arriba','derecha'][i]+'">'+a+'</button>').join('')+'</div><div id="rhythmcover" class="hidden"><div class="rhythm-card"><h2 id="rhythmheading"></h2><p id="rhythmdetail"></p><div id="rhythmactions"></div></div></div>';
document.querySelector('#game').append(root);const $=s=>root.querySelector(s),canvas=$('#rhythmcanvas'),c=canvas.getContext('2d');
function time(){return song.currentTime-chart.start+calibration;}
function cover(title,detail,buttons){$('#rhythmheading').textContent=title;$('#rhythmdetail').textContent=detail;$('#rhythmactions').replaceChildren();for(const [text,action]of buttons){const b=document.createElement('button');b.textContent=text;b.onclick=action;$('#rhythmactions').append(b);}$('#rhythmcover').classList.remove('hidden');}
function finish(){if(!session?.done||reported)return;reported=true;song.pause();paused=true;const r=session.result(),message=options.onComplete(r)||'';cover(r.won?'¡Batalla superada!':'Se agotó tu energía',modes[r.mode].name+' · '+r.accuracy+'% precisión · '+r.score.toLocaleString('es')+' puntos\nPERFECT '+r.counts.perfect+' · SICK '+r.counts.sick+' · GOOD '+r.counts.good+'\nFallos '+(r.counts.miss+r.counts.bad+r.counts.empty)+' · Combo máximo '+r.maxCombo+'\n'+message,[['REPETIR',()=>start(r.mode,options)],['VOLVER AL CONCIERTO',leave]]);}
function press(lane){if(!active||paused||!session||song.paused)return;const t=time(),kind=session.press(lane,t);flash[lane]=.22;if(kind&&kind!=='empty'){pose=4+lane;poseUntil=t+.28;}finish();}
function pause(){if(!active||paused)return;paused=true;song.pause();cover('Batalla en pausa','La música y las flechas se detienen juntas. Tu intento continúa desde aquí.',[['CONTINUAR',resume],['REINICIAR',()=>start(session.mode,options)],['SALIR SIN PREMIO',leave]]);}
function resume(){if(!active||reported)return;$('#rhythmcover').classList.add('hidden');notice='Cargando música…';song.play().then(()=>{paused=false;notice='';}).catch(()=>cover('Toca para continuar','No se pudo iniciar la música.',[['REINTENTAR',resume],['SALIR',leave]]));}
function leave(){if(!active)return;song.pause();active=false;paused=false;root.classList.add('hidden');document.querySelector('#game').classList.remove('rhythmmode');const callback=options?.onExit;session=null;options=null;callback?.();}
function start(mode,opts){if(!modes[mode])return false;options=opts;session=new RhythmSession(mode);reported=false;active=true;paused=true;pose=0;poseUntil=0;flash.fill(0);notice='Cargando música…';document.querySelector('#game').classList.add('rhythmmode');root.classList.remove('hidden');$('#rhythmcover').classList.add('hidden');$('#rhythmtitle').textContent='BATALLA · '+modes[mode].name;window.OmniMusic?.pauseForEvent();song.volume=Math.max(0,Math.min(1,Number(localStorage.getItem('omni-music-volume')??.3)));song.currentTime=chart.start-3;song.play().then(()=>{paused=false;notice='';}).catch(()=>cover('La música necesita un toque','Pulsa CONTINUAR para comenzar la batalla.',[['CONTINUAR',resume],['SALIR',leave]]));return true;}
function drawArrow(x,y,lane,size,alpha=1){c.save();c.translate(x,y);c.rotate([Math.PI*1.5,Math.PI,0,Math.PI*.5][lane]);c.globalAlpha=alpha;c.beginPath();c.moveTo(0,-size);c.lineTo(size,-size*.06);c.lineTo(size*.42,-size*.06);c.lineTo(size*.42,size);c.lineTo(-size*.42,size);c.lineTo(-size*.42,-size*.06);c.lineTo(-size,-size*.06);c.closePath();c.fillStyle=colors[lane];c.fill();c.strokeStyle='#f1ffff';c.lineWidth=2;c.stroke();c.restore();}
function label(text,x,y,size=16,color='#fff',align='center'){c.font='bold '+size+'px Arial';c.textAlign=align;c.fillStyle='#030813';c.fillText(text,x+2,y+2);c.fillStyle=color;c.fillText(text,x,y);}
function render(now){const dt=Math.min(.05,(now-lastFrame)/1000||0);lastFrame=now;if(active&&options){const t=time();if(!paused){session.advance(t);finish();}c.imageSmoothingEnabled=false;const bg=options.background;c.drawImage(bg,0,0,bg.width/2,bg.height/2,0,0,960,540);c.fillStyle='#06081d55';c.fillRect(0,0,960,540);const grad=c.createLinearGradient(400,0,950,0);grad.addColorStop(0,'#080d2277');grad.addColorStop(1,'#080d22ee');c.fillStyle=grad;c.fillRect(420,76,512,454);for(let lane=0;lane<4;lane++){const x=485+lane*125;flash[lane]=Math.max(0,flash[lane]-dt);c.fillStyle=flash[lane]>0?colors[lane]+'35':'#ffffff06';c.fillRect(x-53,93,106,330);c.strokeStyle=colors[lane]+'55';c.strokeRect(x-53,93,106,330);drawArrow(x,430,lane,28,flash[lane]>0?1:.3);}for(let i=session.first;i<session.notes.length;i++){const n=session.notes[i],delta=n.t-t;if(delta>session.rules.lead)break;if(n.result||delta<-.25)continue;const y=430-delta/session.rules.lead*330;drawArrow(485+n.lane*125,y,n.lane,25);}
const info=options.npc,frame=t<poseUntil?pose:Math.floor(Math.max(0,t)*2.2)%2===0?8:9,f=info.table[frame]||info.table[0],h=244,scale=h/info.table[0][3],w=f[2]*scale,dh=f[3]*scale;c.fillStyle='#02041b77';c.beginPath();c.ellipse(220,402,70,15,0,0,Math.PI*2);c.fill();c.drawImage(info.sheet,...f,220-w/2,400-dh,w,dh);label('KIM TAEHYUNG',220,429,14,'#f5d7ff');label('SIGUE LAS FLECHAS',220,450,10,'#cbd5ef');const j=session.lastJudge;if(j&&t-j.time<.7)label(j.kind==='empty'?'FUERA DE RITMO':j.kind.toUpperCase(),220,154,26,['perfect','sick'].includes(j.kind)?'#d1ff9a':j.kind==='good'?'#9be9ff':'#ff9dbe');if(session.combo>1)label(session.combo+' COMBO',220,179,17,'#fff');let remaining=Math.max(0,chart.duration-Math.max(0,t));$('#rhythmhp').style.width=session.health+'%';$('#rhythmhealth').textContent='ENERGÍA '+Math.ceil(session.health)+' / 100';$('#rhythmscore').textContent=session.score.toLocaleString('es')+' PTS · '+Math.floor(remaining/60)+':'+String(Math.ceil(remaining%60)).padStart(2,'0');if(t<0)label(''+Math.ceil(-t),680,274,60,'#e8ffc7');else if(notice)label(notice,680,270,18);else if(!paused&&session.notes[session.first]?.t-t>4)label('INTERLUDIO · PREPÁRATE',680,270,16,'#dec9ef');}requestAnimationFrame(render);}
for(const b of root.querySelectorAll('[data-lane]'))b.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();press(+b.dataset.lane);});$('#rhythmpause').onclick=pause;
document.addEventListener('keydown',e=>{if(!active)return;e.preventDefault();e.stopImmediatePropagation();if(e.repeat)return;if(e.key==='Escape'){paused?resume():pause();return;}const lane=['ArrowLeft','ArrowDown','ArrowUp','ArrowRight'].indexOf(e.key);if(lane>=0)press(lane);else {const k=['a','s','w','d'].indexOf(e.key.toLowerCase());if(k>=0)press(k);}},true);
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',pause);song.addEventListener('waiting',()=>{notice='Cargando música…';});song.addEventListener('playing',()=>notice='');song.addEventListener('error',()=>{if(active){paused=true;cover('No se pudo reproducir la canción','Tu progreso está a salvo. Sal y vuelve a entrar al concierto.',[['VOLVER',leave]]);}});song.addEventListener('ended',()=>{if(active&&!reported){session.advance(chart.duration);finish();}});
window.OmniRhythm={start,pause,resume,leave,get active(){return active},get paused(){return paused},get session(){return session},get song(){return location.search.includes('qa=1')?song:null},modes,chart,calibrate(ms){calibration=Math.max(-.15,Math.min(.15,Number(ms)/1000||0));localStorage.setItem('omni-rhythm-offset',String(calibration));},get offset(){return Math.round(calibration*1000)}};if(location.search.includes('qa=1')){window.OmniRhythm.Session=RhythmSession;window.OmniRhythm.testFinish=finish;window.OmniRhythm.testPress=press;}
requestAnimationFrame(render);
})();
