'use strict';
// Offline synthesized effects: no audio download, microphone or external service.
(()=>{let context,fx,air,wind,active=false,enabled=true,foot=0,chirp=0,lastZone=-1;const level=k=>{const raw=localStorage.getItem('omni-volume-'+k);return raw===null?(k==='sfx'?.5:.18):Math.max(0,Math.min(1,Number(raw)||0));};const volumes={sfx:level('sfx'),ambient:level('ambient')};
function ensure(){if(context){if(context.state==='suspended')context.resume().catch(()=>{});return true;}try{context=new(window.AudioContext||window.webkitAudioContext)();fx=context.createGain();air=context.createGain();fx.connect(context.destination);air.connect(context.destination);fx.gain.value=enabled?volumes.sfx:0;air.gain.value=0;const buf=context.createBuffer(1,context.sampleRate*3,context.sampleRate),v=buf.getChannelData(0);let brown=0;for(let i=0;i<v.length;i++){brown=(brown+(Math.random()*2-1)*.025)/1.025;v[i]=brown;}wind=context.createBufferSource();wind.buffer=buf;wind.loop=true;const filter=context.createBiquadFilter();filter.type='lowpass';filter.frequency.value=700;wind.connect(filter);filter.connect(air);wind.start();return true;}catch(e){return false;}}
function tone(freq,duration=.12,type='sine',vol=.035,bus){if(!enabled||!ensure())return;const o=context.createOscillator(),g=context.createGain(),now=context.currentTime;o.type=type;o.frequency.setValueAtTime(freq,now);o.frequency.exponentialRampToValueAtTime(Math.max(30,freq*.55),now+duration);g.gain.setValueAtTime(Math.max(.001,vol),now);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g);g.connect(bus||fx);o.start();o.stop(now+duration);o.onended=()=>{o.disconnect();g.disconnect();};}
function noise(duration,freq,volume){if(!enabled||!ensure())return;const b=context.createBuffer(1,Math.ceil(context.sampleRate*duration),context.sampleRate),data=b.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);const source=context.createBufferSource(),filter=context.createBiquadFilter(),gain=context.createGain();source.buffer=b;filter.type='lowpass';filter.frequency.value=freq;gain.gain.value=volume;source.connect(filter);filter.connect(gain);gain.connect(fx);source.start();source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();};}
function play(type){if(!active||!enabled)return;if(type==='music'){tone(440,.17,'triangle',.025);tone(660,.2,'sine',.025);tone(880,.24,'sine',.02);}else if(type==='fire'){noise(.36,1600,.12);tone(105,.25,'sine',.06);}else if(type==='crystal'){tone(1300,.21,'triangle',.035);tone(1980,.32,'sine',.025);noise(.05,4000,.025);}else if(type==='spit'){tone(340,.18,'sine',.065);tone(140,.12,'triangle',.04);noise(.12,900,.06);}else if(type==='hit'){noise(.075,700,.07);tone(90,.085,'triangle',.045);}else{noise(.13,1200,.06);tone(170,.12,'sine',.04);}}
function step(dt,moving,surface,speed){if(!active||!moving){foot=0;return;}foot-=dt;if(foot<=0){foot+=Math.max(.18,.36*220/speed);noise(.07,surface==='forest'?1700:surface==='wood'?700:1100,.038);tone(surface==='wood'?165:surface==='stone'?115:80,.075,'sine',.022);}}
function ambient(on,sound,zone,day){active=!!on;enabled=!!sound;if(!context)return;const now=context.currentTime;fx.gain.setTargetAtTime(enabled?volumes.sfx:0,now,.04);air.gain.setTargetAtTime(active&&enabled?volumes.ambient*(zone===9?.18:zone===8?.42:.8):0,now,.15);if(!active||!enabled)return;if(lastZone!==zone){lastZone=zone;chirp=0;}if(zone<3&&day!=='día'&&now>chirp){chirp=now+1.4+Math.random()*2;tone(2700+Math.random()*600,.085,'sine',.045,air);}}
function setVolume(kind,value){if(!(kind in volumes))return;volumes[kind]=Math.max(0,Math.min(1,Number(value)||0));localStorage.setItem('omni-volume-'+kind,String(volumes[kind]));}
document.addEventListener('pointerdown',ensure,{passive:true});document.addEventListener('keydown',ensure);document.addEventListener('visibilitychange',()=>{if(document.hidden){active=false;if(air)air.gain.setTargetAtTime(0,context.currentTime,.01);}});
window.OmniSound={play,step,ambient,tone,noise,setVolume,get volumes(){return {...volumes}},get active(){return active},get levels(){return context?{sfx:fx.gain.value,ambient:air.gain.value,state:context.state}:null}};
})();
