'use strict';
// Generated by tools/import_watch_layers.py. Do not edit by hand.
window.OMNI_WATCH_LAYERS = {"completed":{"core":{"src":"assets/wl-completed-core.webp","w":512,"h":512}},"prototype":{"core":{"src":"assets/wl-prototype-core.webp","w":512,"h":512}},"recalibrated":{"body":{"src":"assets/wl-recalibrated-body.webp","w":366,"h":366},"core":{"src":"assets/wl-recalibrated-core.webp","w":128,"h":128}},"ultimatrix":{"core":{"src":"assets/wl-ultimatrix-core.webp","w":284,"h":284}}};
